### ISSUE TITLE
problem rendering markdown constructors

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/githubpages-doc-guidelines#1]
- [ ] For some reason, the Markdown constructors are not rendered in rich text format.
- [ ] Also, Facebook was added to the `settings.json` file but it is not displayed.

![image](https://user-images.githubusercontent.com/3258579/143380246-5582cd4b-571a-4b9d-aa9f-209192a3873b.png)

**Comment by rubystream** [comment]
The [settings](https://content.nuxtjs.org/themes/docs#settings)  have list of defined *theme* properties and facebook is not part of them.

**Comment by rubystream** [comment]
Based on  [Table of Contents](https://content.nuxtjs.org/writing#table-of-contents) info the *theme* is using only only h2 and h3 titles are used for the toc.

**Comment by rubystream** [comment]
Fix header rendering with PR #2

**Comment by rubystream** [comment]
YouTube is not part of the original *theme*. In order to add that one the custom component must be added that will overload the *theme* header one like it was done [https://guidelines.openmobilealliance.org/](https://guidelines.openmobilealliance.org/).

**Comment by jpradocueva** [comment]
@rubystream thanks! now I see what should be the default code. The interesting aspect is that I was following the installation from scratch and the settings were set by default.
